//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nmvm.Models.nmvm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string EmployeeNumber { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string WorkPhone { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Profession { get; set; }
        public Nullable<int> BirthYear { get; set; }
        public string Gender { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatedByDisplayName { get; set; }
        public string CreatedByUserName { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public string ModifiedByDisplayName { get; set; }
        public string ModifiedByUserName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
