//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nmvm.Models.nmvm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public int Id { get; set; }
        public int UnitId { get; set; }
        public string PositionTitle { get; set; }
        public string PositionNumber { get; set; }
        public string AwardCode { get; set; }
        public string Grade { get; set; }
        public decimal FteApproved { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatedByDisplayName { get; set; }
        public string CreatedBySystemName { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public string ModifiedByDisplayName { get; set; }
        public string ModifiedBySystemName { get; set; }
    }
}
