//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nmvm.Models.nmvm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reference
    {
        public int Id { get; set; }
        public string DomainCode { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Label { get; set; }
        public System.DateTime EffectiveFromDateTime { get; set; }
        public Nullable<System.DateTime> EffectiveToDateTime { get; set; }
        public bool ActiveFlag { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatedByDisplayName { get; set; }
        public string CreatedByUserName { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public string ModifiedByDisplayName { get; set; }
        public string ModifiedByUserName { get; set; }
    }
}
