//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nmvm.Models.nmvm
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string PreferredName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatedByUserName { get; set; }
        public string CreatedByDisplaName { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public string ModifiedByUserName { get; set; }
        public string ModifiedByDisplaName { get; set; }
    }
}
