CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1), 
    [Username] VARCHAR(255) NOT NULL, 
    [FirstName] VARCHAR(255) NOT NULL, 
    [LastName] VARCHAR(255) NOT NULL, 
    MiddleName VARCHAR(255) NULL,
    PreferredName VARCHAR(255) NULL,
    [Email] VARCHAR(255) NOT NULL, 
    [Mobile] VARCHAR(50) NULL, 
    [CreatedDateTime] DATETIME NOT NULL DEFAULT SYSDATETIME(), 
    [CreatedByUserName] VARCHAR(255) NOT NULL DEFAULT SYSTEM_USER, 
    [CreatedByDisplaName] VARCHAR(255) NOT NULL DEFAULT SYSTEM_USER,
    [ModifiedDateTime] DATETIME NOT NULL DEFAULT SYSDATETIME(), 
    [ModifiedByUserName] VARCHAR(255) NOT NULL DEFAULT SYSTEM_USER, 
    [ModifiedByDisplaName] VARCHAR(255) NOT NULL DEFAULT SYSTEM_USER
)
